- hosts: ios
  tasks:
    - name: Configure login message of the day on all MOD network devices
      cisco.ios.ios_banner:
        banner: login
        text: |
          =================================================
          Welcome to the MOD NetDevOps Project
          All devices in this lab are configured by Ansible
          All configurations are for demonstration purposes 
          This does not reflect operational networks
          =================================================

- hosts: switches
  tasks:
    - name: Create VLANS on MOD switches
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: STAFFORDSHIRE_VLAN
            shutdown: disabled
          - vlan_id: 20
            name: UNIVERSITY_VLAN
            shutdown: disabled
          - vlan_id: 30
            name: PROJECT_VLAN
            shutdown: disabled


- hosts: ios
  tasks:
    - name: Copy running config to startup config after modifications
      cisco.ios.ios_config:
        save_when: modified
